baseURL = 'https://mirio.dev'
languageCode = 'en-us'
title = "cole's blog"

[module]
[[module.imports]]
path = "github.com/nanxiaobei/hugo-paper"

author = 'Cole MacKenzie'
DefaultContentLanguage = "en"
enableInlineShortcodes = true

enableGitInfo = true

[params]
color = 'linen'
github = 'cmackenzie1'
avatar = 'gravatar@mirio.dev'
twitter = '@Cole_MacKenzie'
name = 'Cole MacKenzie'
bio = 'Software Engineer that likes to build things. All views are my own.'

[permalinks]
posts = '/:year/:month/:day/:slug'
